version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Universal
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
  - iwa
  labels:
  - dependencies
  ignore:
  - dependency-name: popyt
    versions:
    - ">= 3.1.a"
    - "< 3.2"
  - dependency-name: popyt
    versions:
    - ">= 3.3.a"
    - "< 3.4"
