name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node v12
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12

    - name: deps cache
      uses: actions/cache@v1.1.2
      with:
        path: node_modules/
        key: ${{ runner.os }}-yarn

    - name: install dependencies
      run: sudo yarn

    - name: run tsc
      run: |
        sudo yarn global add typescript
        tsc

    - name: upload build files
      uses: actions/upload-artifact@v2
      with:
        path: build/

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node v12
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12

    - name: download build files
      uses: actions/download-artifact@v2
      with:
        path: build/

    - name: run eslint
      run: |
        sudo yarn global add eslint
        eslint build/**/*.js
